export interface NavItem {
  label: string;
  href: string;
  icon: string;
}

export interface PortalConfig {
  title: string;
  subtitle: string;
  avatarLetter: string;
  avatarColor: string;
  themeClass: string;
  accentColor: string;
  navItems: NavItem[];
}

export const portals = [
  {
    href: "/student",
    label: "Student Portal",
    icon: "🎓",
    desc: "AI Tutor, Adaptive Learning, Quizzes, Career Guidance",
    color: "from-indigo-600 to-purple-600",
    border: "border-indigo-500/30",
    bg: "hover:bg-indigo-500/10",
  },
  {
    href: "/parent",
    label: "Parent Portal",
    icon: "👨‍👩‍👧",
    desc: "Child Performance, Notifications, AI Parent Assistant",
    color: "from-emerald-600 to-teal-600",
    border: "border-emerald-500/30",
    bg: "hover:bg-emerald-500/10",
  },
  {
    href: "/teacher",
    label: "Teacher Portal",
    icon: "📚",
    desc: "AI Lesson Planner, Question Generator, Student Analytics",
    color: "from-amber-600 to-orange-600",
    border: "border-amber-500/30",
    bg: "hover:bg-amber-500/10",
  },
  {
    href: "/headmaster",
    label: "Headmaster Portal",
    icon: "🏫",
    desc: "School Management, Staff, Resources, Enrollment",
    color: "from-blue-600 to-cyan-600",
    border: "border-blue-500/30",
    bg: "hover:bg-blue-500/10",
  },
  {
    href: "/block-education-officer",
    label: "Block Education Officer",
    icon: "🏢",
    desc: "School Comparisons, Attendance & Exam Analytics",
    color: "from-violet-600 to-purple-600",
    border: "border-violet-500/30",
    bg: "hover:bg-violet-500/10",
  },
  {
    href: "/district-education-officer",
    label: "District Education Officer",
    icon: "🗺️",
    desc: "District Dashboard, Dropout Heatmap, School Ranking",
    color: "from-pink-600 to-rose-600",
    border: "border-pink-500/30",
    bg: "hover:bg-pink-500/10",
  },
  {
    href: "/commissioner",
    label: "Commissioner Portal",
    icon: "⚖️",
    desc: "State Operations, Policy Monitoring, Budget Utilization",
    color: "from-cyan-600 to-sky-600",
    border: "border-cyan-500/30",
    bg: "hover:bg-cyan-500/10",
  },
  {
    href: "/minister",
    label: "Minister Dashboard",
    icon: "🏛️",
    desc: "Executive Command Center, Live State View, KPI Monitoring",
    color: "from-red-600 to-orange-600",
    border: "border-red-500/30",
    bg: "hover:bg-red-500/10",
  },
  {
    href: "/super-admin",
    label: "Super Admin",
    icon: "🛠️",
    desc: "Manage Custom Pages, Enable/Disable Features, View Logs",
    color: "from-slate-700 to-slate-900",
    border: "border-slate-500/30",
    bg: "hover:bg-slate-500/10",
  },
];

export const roleConfigs: Record<string, PortalConfig> = {
  STUDENT: {
    title: "Student Portal",
    subtitle: "Welcome back, Arjun Kumar · Class 10A · EMIS: 3301234567",
    avatarLetter: "A",
    avatarColor: "#6366f1",
    themeClass: "theme-student",
    accentColor: "#6366f1",
    navItems: [
      { label: "Portal Home", href: "/student", icon: "🏠" },
    ],
  },
  STUDENT_MIDDLE: {
    title: "Middle School Dashboard",
    subtitle: "Welcome back, Arjun! · Class 7B · You have 5 new badges waiting! 🌟",
    avatarLetter: "A",
    avatarColor: "#10b981",
    themeClass: "theme-student",
    accentColor: "#10b981",
    navItems: [
      { label: "Dashboard", href: "/student/middle-school", icon: "🏠" },
      { label: "My Subjects", href: "/student/subjects", icon: "📖" },
      { label: "Homework", href: "/student/homework", icon: "📝" },
      { label: "My Badges", href: "/student/middle-school/badges", icon: "🏅" },
      { label: "Fun Quizzes", href: "/student/middle-school/quizzes", icon: "🎮" },
      { label: "Story Books", href: "/student/middle-school/stories", icon: "📚" },
      { label: "AI Helper", href: "/student/middle-school/ai", icon: "🤖" },
      { label: "Welfare & Benefits", href: "/student/middle-school/welfare", icon: "🎁" },

      // Common Student Menu
      { label: "---", href: "#", icon: "" },
      { label: "Common Tools", href: "#", icon: "" },
      { label: "Announcements", href: "/student/announcements", icon: "📢" },
      { label: "Virtual Labs", href: "/student/labs", icon: "🧪" },
      { label: "Digital Portfolio", href: "/student/middle-school/portfolio", icon: "🗂️" },
      { label: "Extracurriculars", href: "/student/activities", icon: "🎭" },
      { label: "Sports & Athletics", href: "/student/sports", icon: "⚽" },
      { label: "Wellness", href: "/student/wellness", icon: "💚" },
      // { label: "Coding Academy", href: "/student/coding", icon: "💻" },
      { label: "Learning Platform", href: "/student/middle-school/learning-platform", icon: "💻" },
    ],
  },
  STUDENT_HIGH: {
    title: "High School Dashboard",
    subtitle: "Welcome, Arjun · Class 10A · Focus Area: SSLC Board Preparation",
    avatarLetter: "A",
    avatarColor: "#ef4444",
    themeClass: "theme-student",
    accentColor: "#ef4444",
    navItems: [
      { label: "Dashboard", href: "/student/high-school", icon: "🏠" },
      { label: "My Subjects", href: "/student/subjects", icon: "📖" },
      { label: "Homework", href: "/student/homework", icon: "📝" },
      { label: "Board Prep", href: "/student/high-school/board-prep", icon: "🎯" },
      { label: "Mock Tests", href: "/student/high-school/mock-tests", icon: "📝" },
      { label: "Study Boost", href: "/student/high-school/study-boost", icon: "⚡" },
      { label: "Career Aptitude", href: "/student/high-school/career", icon: "🧭" },
      { label: "Scholarships", href: "/student/high-school/scholarships", icon: "🎓" },

      // Common Student Menu
      { label: "---", href: "#", icon: "" },
      { label: "Common Tools", href: "#", icon: "" },
      { label: "Announcements", href: "/student/announcements", icon: "📢" },
      { label: "AI Tutor", href: "/student/ai-tutor", icon: "🤖" },
      { label: "Virtual Labs", href: "/student/labs", icon: "🧪" },
      { label: "Digital Portfolio", href: "/student/portfolio", icon: "🗂️" },
      { label: "Extracurriculars", href: "/student/activities", icon: "🎭" },
      { label: "Sports & Athletics", href: "/student/sports", icon: "⚽" },
      { label: "Wellness", href: "/student/wellness", icon: "💚" },
      { label: "Learning Platform", href: "/student/high-school/learning-platform", icon: "💻" },
    ],
  },
  STUDENT_HIGHER: {
    title: "Higher Secondary Dashboard",
    subtitle: "Welcome, Arjun · Class 12 Biology Stream · Target: Medical Colleges",
    avatarLetter: "A",
    avatarColor: "#8b5cf6",
    themeClass: "theme-student",
    accentColor: "#8b5cf6",
    navItems: [
      { label: "Dashboard", href: "/student/higher-secondary", icon: "🏠" },
      { label: "My Subjects", href: "/student/subjects", icon: "📖" },
      { label: "Homework", href: "/student/homework", icon: "📝" },
      { label: "Board Prep", href: "/student/higher-secondary/board-prep", icon: "🎯" },
      { label: "NEET/JEE Prep", href: "/student/higher-secondary/competitive", icon: "🚀" },
      { label: "Mock Tests", href: "/student/higher-secondary/mock-tests", icon: "📝" },
      { label: "College Admissions", href: "/student/higher-secondary/admissions", icon: "🎓" },
      { label: "Scholarships", href: "/student/higher-secondary/scholarships", icon: "📜" },

      // Common Student Menu
      { label: "---", href: "#", icon: "" },
      { label: "Common Tools", href: "#", icon: "" },
      { label: "Announcements", href: "/student/announcements", icon: "📢" },
      { label: "AI Tutor", href: "/student/ai-tutor", icon: "🤖" },
      { label: "Virtual Labs", href: "/student/labs", icon: "🧪" },
      { label: "Digital Portfolio", href: "/student/portfolio", icon: "🗂️" },
      { label: "Extracurriculars", href: "/student/activities", icon: "🎭" },
      { label: "Sports & Athletics", href: "/student/sports", icon: "⚽" },
      { label: "Wellness", href: "/student/wellness", icon: "💚" },
      { label: "Learning Platform", href: "/student/higher-secondary/learning-platform", icon: "💻" },
    ],
  },
  TEACHER: {
    title: "Teacher Dashboard",
    subtitle: "Mrs. Sumathi Devi · Mathematics · GHS Coimbatore",
    avatarLetter: "S",
    avatarColor: "#f59e0b",
    themeClass: "theme-teacher",
    accentColor: "#f59e0b",
    navItems: [
      { label: "My Classes", href: "/teacher/classes", icon: "🏫" },
      { label: "Science Labs", href: "/teacher/labs", icon: "🧪" },
      { label: "Subject Analytics", href: "/teacher/subject-analytics", icon: "📊" },

      // Common Menu & Tools
      { label: "Admin & Tools", href: "#", icon: "" },
      { label: "AI Lesson Planner", href: "/teacher/lesson-planner", icon: "📋" },
      { label: "Question Generator", href: "/teacher/questions", icon: "❓" },
      { label: "AI Evaluation", href: "/teacher/evaluation", icon: "✅" },

      // Student Management
      { label: "Student Management", href: "#", icon: "" },
      { label: "Student Profiles", href: "/teacher/student-profiles", icon: "👤" },
      { label: "Student Status", href: "/teacher/student-status", icon: "📈" },
      { label: "Homework Manager", href: "/teacher/homework", icon: "✔️" },
      { label: "Scholarship Details", href: "/teacher/scholarships", icon: "🎓" },
      { label: "Student Analytics", href: "/teacher/analytics", icon: "📊" },
      { label: "Risk Alerts", href: "/teacher/risk-alerts", icon: "⚠️" },
      { label: "Parent Management", href: "/teacher/parents", icon: "👪" },

      // Resources & Admin
      { label: "Resources & Admin", href: "#", icon: "" },
      // { label: "AI Material Hub", href: "/teacher/material-hub", icon: "✨" },
      { label: "Add Materials", href: "/teacher/add-materials", icon: "📚" },
      { label: "Daily Attendance", href: "/teacher/attendance", icon: "📅" },
      { label: "Announcements", href: "/teacher/announcements", icon: "📢" },
      { label: "Leave Requests", href: "/teacher/leave", icon: "📄" },
      { label: "My Subjects (Science)", href: "/teacher", icon: "🔬" },
    ],
  },
  PARENT: {
    title: "Parent Portal",
    subtitle: "Rajesh Kumar · Parent of Priya · Class 9B",
    avatarLetter: "R",
    avatarColor: "#10b981",
    themeClass: "theme-parent",
    accentColor: "#10b981",
    navItems: [
      { label: "Dashboard", href: "/parent", icon: "🏠" },
      { label: "Child Performance", href: "/parent/performance", icon: "📊" },
      { label: "Attendance", href: "/parent/attendance", icon: "📅" },
      { label: "Homework Status", href: "/parent/homework", icon: "📝" },
      { label: "Notifications", href: "/parent/notifications", icon: "🔔" },
      { label: "AI Assistant", href: "/parent/ai-assistant", icon: "🤖" },
      { label: "Scholarship", href: "/parent/scholarship", icon: "🎓" },
      { label: "PTA Meetings", href: "/parent/pta", icon: "🤝" },
    ],
  },
  HEADMASTER: {
    title: "Headmaster Portal",
    subtitle: "Mr. Venkatesh R. · GHS Coimbatore · DISE: 33012345",
    avatarLetter: "V",
    avatarColor: "#3b82f6",
    themeClass: "theme-headmaster",
    accentColor: "#3b82f6",
    navItems: [
      { label: "Dashboard", href: "/headmaster", icon: "🏠" },

      { label: "People & Staff", href: "#", icon: "" },
      { label: "Student Monitoring", href: "/headmaster/students", icon: "👨‍🎓" },
      { label: "Staff Management", href: "/headmaster/staff", icon: "👩‍🏫" },
      { label: "Temporary Staff", href: "/headmaster/temporary-staff", icon: "🤝" },
      { label: "Parents Details", href: "/headmaster/parents", icon: "👪" },
      { label: "School Alumni", href: "/headmaster/alumni", icon: "🎓" },

      { label: "Academics & Records", href: "#", icon: "" },
      { label: "Attendance", href: "/headmaster/attendance", icon: "📅" },
      { label: "Timetable", href: "/headmaster/timetable", icon: "🗓️" },
      { label: "Exam Schedule", href: "/headmaster/exams", icon: "📋" },
      { label: "Model Exam Results", href: "/headmaster/model-exams", icon: "📝" },

      { label: "School Admin & Govt", href: "#", icon: "" },
      { label: "School Resources", href: "/headmaster/resources", icon: "🏗️" },
      { label: "Mid-Day Meal", href: "/headmaster/midday-meal", icon: "🍛" },
      { label: "Scholarship", href: "/headmaster/scholarship", icon: "🏅" },
      { label: "Govt Schemes Update", href: "/headmaster/gov-schemes", icon: "🏛️" },

      { label: "Extra Curricular & Info", href: "#", icon: "" },
      { label: "School Events", href: "/headmaster/events", icon: "🎉" },
      { label: "Media Gallery", href: "/headmaster/gallery", icon: "🖼️" },
      { label: "Rewards & Honors", href: "/headmaster/rewards", icon: "🏆" },
      { label: "School History", href: "/headmaster/history", icon: "📜" },
    ],
  },
  BEO: {
    title: "Block Education Officer",
    subtitle: "Mr. Murugesan P. · Coimbatore South Block",
    avatarLetter: "M",
    avatarColor: "#8b5cf6",
    themeClass: "theme-beo",
    accentColor: "#8b5cf6",
    navItems: [
      { label: "Dashboard", href: "/block-education-officer", icon: "🏠" },
      { label: "Manage Headmasters", href: "/block-education-officer/headmasters", icon: "🏫" },
      { label: "School Comparisons", href: "/block-education-officer/schools", icon: "🏫" },
      { label: "Attendance Analytics", href: "/block-education-officer/attendance", icon: "📅" },
      { label: "Exam Analytics", href: "/block-education-officer/exams", icon: "📊" },
      { label: "Infrastructure", href: "/block-education-officer/infrastructure", icon: "🏗️" },
      { label: "Teacher Deployment", href: "/block-education-officer/teachers", icon: "👩‍🏫" },
      { label: "Dropouts Tracking", href: "/block-education-officer/dropouts", icon: "📉" },
      { label: "Schemes Update", href: "/block-education-officer/schemes", icon: "📜" },
      { label: "Grievances", href: "/block-education-officer/grievances", icon: "⚖️" },
      { label: "Financial Reports", href: "/block-education-officer/financials", icon: "💰" },
      { label: "Circulars", href: "/block-education-officer/circulars", icon: "📢" },
    ],
  },
  DEO: {
    title: "District Education Officer",
    subtitle: "DEO Officer · Coimbatore District",
    avatarLetter: "D",
    avatarColor: "#ec4899",
    themeClass: "theme-deo",
    accentColor: "#ec4899",
    navItems: [
      { label: "Dashboard", href: "/district-education-officer", icon: "🏠" },
      { label: "Manage BEOs", href: "/district-education-officer/beos", icon: "🏢" },
      { label: "District Overview", href: "/district-education-officer/overview", icon: "🗺️" },
      { label: "School Rankings", href: "/district-education-officer/rankings", icon: "🏆" },
      { label: "Dropout Heatmap", href: "/district-education-officer/dropout", icon: "🔴" },
      { label: "Teacher Analytics", href: "/district-education-officer/teachers", icon: "👩‍🏫" },
      { label: "Scholarship Tracking", href: "/district-education-officer/scholarship", icon: "🎓" },
      { label: "Learning Outcomes", href: "/district-education-officer/outcomes", icon: "📈" },
      { label: "Block Comparisons", href: "/district-education-officer/blocks", icon: "📊" },
      { label: "Schemes Tracking", href: "/district-education-officer/schemes", icon: "📜" },
      { label: "Infrastructure", href: "/district-education-officer/infrastructure", icon: "🏗️" },
      { label: "Grievances", href: "/district-education-officer/grievances", icon: "⚖️" },
      { label: "Circulars", href: "/district-education-officer/circulars", icon: "📢" },
    ],
  },
  COMMISSIONER: {
    title: "Commissioner Portal",
    subtitle: "Commissioner · State Operations",
    avatarLetter: "C",
    avatarColor: "#06b6d4",
    themeClass: "theme-commissioner",
    accentColor: "#06b6d4",
    navItems: [
      { label: "Dashboard", href: "/commissioner", icon: "🏠" },
      { label: "Manage DEOs", href: "/commissioner/deos", icon: "🗺️" },
      { label: "District Comparisons", href: "/commissioner/districts", icon: "🗺️" },
      { label: "Policy Monitoring", href: "/commissioner/policy", icon: "⚖️" },
      { label: "Budget Utilization", href: "/commissioner/budget", icon: "💰" },
      { label: "School Performance", href: "/commissioner/performance", icon: "📊" },
      { label: "Infrastructure Score", href: "/commissioner/infrastructure", icon: "🏗️" },
      { label: "State Analytics", href: "/commissioner/analytics", icon: "📈" },
      { label: "Teacher Deployment", href: "/commissioner/teachers", icon: "👩‍🏫" },
      { label: "Schemes Overview", href: "/commissioner/schemes", icon: "📜" },
      { label: "Grievances Redressal", href: "/commissioner/grievances", icon: "⚖️" },
      { label: "Announcements", href: "/commissioner/announcements", icon: "📢" },
    ],
  },
  MINISTER: {
    title: "Minister Dashboard",
    subtitle: "Minister · Executive Command Center",
    avatarLetter: "M",
    avatarColor: "#ef4444",
    themeClass: "theme-minister",
    accentColor: "#ef4444",
    navItems: [
      { label: "Command Center", href: "/minister", icon: "🏛️" },
      { label: "Manage Commissioners", href: "/minister/commissioners", icon: "⚖️" },
      { label: "Live State View", href: "/minister/live", icon: "📡" },
      { label: "KPI Monitoring", href: "/minister/kpi", icon: "📊" },
      { label: "AI Predictions", href: "/minister/predictions", icon: "🤖" },
      { label: "District Reports", href: "/minister/districts", icon: "🗺️" },
      { label: "Policy Intelligence", href: "/minister/policy", icon: "💡" },
      { label: "Budget Overview", href: "/minister/budget", icon: "💰" },
      { label: "Schemes Progress", href: "/minister/schemes", icon: "📜" },
      { label: "Infrastructure Projects", href: "/minister/infrastructure", icon: "🏗️" },
      { label: "Public Grievances", href: "/minister/grievances", icon: "⚖️" },
      { label: "Press & Media", href: "/minister/media", icon: "📰" },
    ],
  },
  SUPERADMIN: {
    title: "Super Admin Portal",
    subtitle: "System Management & Dynamic Governance",
    avatarLetter: "S",
    avatarColor: "#7c3aed",
    themeClass: "theme-superadmin",
    accentColor: "#7c3aed",
    navItems: [
      { label: "System Dashboard", href: "/super-admin", icon: "📊" },

      { label: "People & Access", href: "#", icon: "" },
      { label: "User Management", href: "/super-admin/users", icon: "👥" },
      { label: "Role & Permissions", href: "/super-admin/roles", icon: "🔐" },
      { label: "School Management", href: "/super-admin/schools", icon: "🏫" },
      { label: "Headmaster Management", href: "/super-admin/headmasters", icon: "👤" },

      { label: "Academics & Content", href: "#", icon: "" },
      { label: "Syllabus Management", href: "/super-admin/syllabus", icon: "📚" },
      { label: "Material Library", href: "/super-admin/materials", icon: "📦" },
      { label: "Department Modules", href: "/super-admin/modules", icon: "🗓️" },

      { label: "System & AI", href: "#", icon: "" },
      { label: "Feature Toggles", href: "/super-admin/features", icon: "🔧" },
      { label: "AI Integration Setup", href: "/super-admin/ai-config", icon: "🤖" },
      { label: "Data Flow Monitor", href: "/super-admin/data-flow", icon: "🔄" },

      { label: "Governance", href: "#", icon: "" },
      { label: "Manage Ministers", href: "/super-admin/ministers", icon: "🏛️" },
      { label: "Page Management", href: "/super-admin/pages", icon: "📄" },
      { label: "Announcements", href: "/super-admin/announcements", icon: "📢" },

      { label: "Audit & Config", href: "#", icon: "" },
      { label: "System Logs", href: "/super-admin/logs", icon: "📋" },
      { label: "Portal Settings", href: "/super-admin/settings", icon: "⚙️" },
    ],
  },
};
